update based on the gitdb changes
workaround gitdb/util.py error: 
" AttributeError: 'Commit' object has no attribute 'authored_datetime' "
and therefore the fix:
authored_datetime became authored_date